name: Purge jsDelivr Cache

on:
  push:
    branches: [main]

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr CDN cache
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/ECH0-STUDIO/webflow-scripts@main/phu-tai-jsc/global.js"
          curl -X GET "https://purge.jsdelivr.net/gh/ECH0-STUDIO/webflow-scripts@main/phu-tai-jsc/pages/home.js"
